// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3FKY5yYZN-EqrpEyZMpnJjTkaJyY310',
    appId: 'AIzaSyAw3FKY5yYZN-EqrpEyZMpnJjTkaJyY310',
    messagingSenderId: '854117481642',
    projectId: 'flutter-uiux-93c6c',
    authDomain: 'flutter-uiux-93c6c.firebaseapp.com',
    storageBucket: 'flutter-uiux-93c6c.appspot.com',
    measurementId: 'G-X43CYR4ZNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvRXS5CfFm4zLirmLv0d5e4lafVS7jlek',
    appId: '1:854117481642:android:78231856b5f1e6d10564d3',
    messagingSenderId: '854117481642',
    projectId: 'flutter-uiux-93c6c',
    storageBucket: 'flutter-uiux-93c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qPdNTHnd6qUlvT9DZtGngMbDTYUws4U',
    appId: '1:854117481642:ios:5613a5eb757a68160564d3',
    messagingSenderId: '854117481642',
    projectId: 'flutter-uiux-93c6c',
    storageBucket: 'flutter-uiux-93c6c.appspot.com',
    iosBundleId: 'com.example.traveldiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qPdNTHnd6qUlvT9DZtGngMbDTYUws4U',
    appId: '1:854117481642:ios:c0ec6f6f0e68a2290564d3',
    messagingSenderId: '854117481642',
    projectId: 'flutter-uiux-93c6c',
    storageBucket: 'flutter-uiux-93c6c.appspot.com',
    iosBundleId: 'com.example.traveldiary.RunnerTests',
  );
}
